### PR TITLE
Making a wrong right again

### PR DESCRIPTION
**Pull request by tobi**
Context: ShopQI is a Chinese clone of Shopify. I went ahead and improved it.

### CODE REVIEW

**Comment by airhorns** [comment]
:+1: LGTM

**Comment by pushmatrix** [comment]
:shipit: ship it

**Comment by jaehess** [comment]
+1

**Comment by peteforde** [comment]
Fuck it, I'd fund that.

**Comment by romanblick** [comment]
+1

**Comment by duff** [comment]
+1

**Comment by joshgosse** [comment]
+∞

**Comment by silent1mezzo** [comment]
+1

**Comment by edward** [comment]
@tobi no tests?

**Comment by EricHogue** [comment]
+1

**Comment by burke** [comment]
:+1:

**Comment by matthelm** [comment]
+1

**Comment by sgonyea** [comment]
Because China.

**Comment by iamwilhelm** [comment]
+1

**Comment by ghost** [comment]
so... what's plan b again?

**Comment by JamieS** [comment]
Definitely an improvement!

**Comment by mattroberts** [comment]
+1

**Comment by Soleone** [comment]
- 0 additions
- 96,287 deletions

These are the best types of commits. :clap:

**Comment by carolineschnapp** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by DavidToca** [comment]
best pull request ever :)

**Comment by buffpojken** [comment]
Go for it!

**Comment by masom** [comment]
+1

**Comment by jdan** [comment]
+1

**Comment by Kingfox** [comment]
+1

**Comment by mikehostetler** [comment]
+1000 Internets!

**Comment by cmcdonaldca** [comment]
++++1

**Comment by danielw** [comment]
I approve of this pull request

**Comment by ryanlanglois** [comment]
lol

**Comment by davidcelis** [comment]
Please resubmit with tests

**Comment by rgurley** [comment]
I found even more websites ripping off Shopify's UI!

http://cdn.shopify.com/static/images/icons/ft-security.png
http://fortthompson.co/images/FT_Security_Lock.png

http://cdn.shopify.com/static/images/icons/ft-cdn.png
http://images.apple.com/jp/support/images/dotmac_logo.gif

**Comment by Soleone** [comment]
@rgurley

not sure if trolling or trying to be funny

**Comment by dashed** [comment]
Hi Reddit.

**Comment by orospakr** [comment]
So, it certainly appears (from the reports I've read; I've not gone and compared it myself yet) that ShopQi ripped off lots of publicly visible frontend code from Shopify.  However, @tobi's merge also backs out all of the backend code.  Presumably ShopQi had to write that bit themselves.

Also, it's kind of surprising that ShopQi pushed its entire source tree here on Github to begin with.

**Comment by hikari-no-yume** [comment]
The code quality of this commit is amazing, it has gone up maybe 100%.

**Comment by Laurelai** [comment]
Best. Commit. Ever.

**Comment by loadx** [comment]
+1

**Comment by Chrisedmo** [comment]
Brilliant! I love Shopify even more now!!

**Comment by wiseleyb** [comment]
Beautiful

**Comment by abronte** [comment]
+1

**Comment by simond** [comment]
at least its open source. is shoppify?

**Comment by Chrisedmo** [comment]
@simond they contribute a lot to OS: https://github.com/Shopify + https://github.com/Shopify/active_merchant

**Comment by raggi** [comment]
Wondering if @tobi is aware his assets and code were also relicensed under AGPL 3!

**Comment by olalonde** [comment]
Ripoff? The guy at least had to write the backend, no? Seems to me that @tobi doesn't like competition. How about you do the same thing on the Diaspora repo and claim they are a Facebook ripoff?

-1

**Comment by silent1mezzo** [comment]
@lenage This is just a statement from @tobi that it's not ok to blatantly copy another person/companies work.

Competition is one thing, a total ripoff is another.

**Comment by datl** [comment]
+1 I saw this on trending repos =)

**Comment by ghost** [comment]
Props to anyone that could build a product end to end. Nothing is original on the internets. Shopify should offer this guy a job to spearhead the Chinese market instead of belittling him.

**Comment by geeknam** [comment]
I approve this pull request :+1:

**Comment by ilake** [comment]
+1 XD

**Comment by jcstringer** [comment]
So awesome.

**Comment by mason-stewart** [comment]
+1 :thumbsup:

**Comment by hisea** [comment]
1. Ripping off design is wrong.
2. Removing the entire open source project including its original parts that are not ripoffs is also wrong.
3. Correct a wrong with another wrong doesn't make anything right.

**Comment by rgurley** [comment]
> Ripping off design is wrong.

O RLY?

http://www.youtube.com/watch?v=zL2FOrx41N0

**Comment by hisea** [comment]
@rgurley 
hmm. .interesting video.

**Comment by GiaoGiaoCat** [comment]
+1

**Comment by pbc** [comment]
+1

**Comment by lukemelia** [comment]
Nicely played.

**Comment by arapehl** [comment]
yolo shipit

**Comment by moechaieb** [comment]
Nice refactor! :+1:

**Comment by sam-obeid** [comment]
Awesome! 🚢

**Comment by jamiemtdwyer** [comment]
Test failures legit?

**Comment by will-r-wang** [comment]
:shipit:

**Pull request closed without merging**
