### PR TITLE
Dependecies update

### PR DESCRIPTION
**Pull request by andriytyurnikov**
dependencies up to date to get app secure and running under OS X

### CODE REVIEW

**Comment by saberma** [comment]
@andriytyurnikov please re-create the pull and assigns the target branch to `master`, not the `develop` branch.

**Comment by andriytyurnikov** [comment]
develop is dead? this commit merges them

**Comment by saberma** [comment]
I don't use develop branch for a long time, and forget to update it.

This PR contains a lots of commits, `Files Changed` list is not clean enough to merge.

**Comment by andriytyurnikov** [comment]
Allright, will create new one.
Perhaps we should remove this branch then :)

**Comment by saberma** [comment]
`develop` branch was deleted, thanks.

**Pull request closed without merging**
